---
title: "B201 DAP2"
author: "Lillian Chen"
date: "12/8/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(MASS)
library(Hmisc)
library(broom)
library(purrr)
library(gtsummary)
library(gt)


```



```{r}
cdidata <- read_csv(file = "cdi_data.csv", show_col_types = F)

table1data <-cdidata %>% 
  dplyr::select(-id, -cty, -state) %>% 
  mutate(region = fct_recode(factor(region), 
                             "Northeast" = "1", 
                             "North Central" = "2", 
                             "South" = "3", 
                             "West" = "4")) %>% 
  labelled::set_variable_labels(area = "Land area (mi)",
                                pop = "Total population",
                                pop18 = "Percent of population aged 18-34",
                                pop65 = "Percent of population aged 65+",
                                docs = "Number of active physicians",
                                beds = "Number of hospital beds",
                                crimes = "Total serious crimes",
                                hsgrad = "Percent high school graduates",
                                bagrad = "Percent bachelor’s degrees",
                                poverty = "Percent below poverty level",
                                unemp = "Percent unemployment",
                                pcincome = "Per capita income (USD)",
                                totalinc = "Total personal income (millions USD)",
                                region = "Geographic region")

# summary characteristics of initial dataset
reset_gtsummary_theme()
theme_gtsummary_journal(journal = "jama")
theme_gtsummary_mean_sd()
theme_gtsummary_compact()

table1data %>% 
  tbl_summary() %>% 
  modify_caption("**Summary of U.S. County Characteristics**") %>% 
  as_gt() %>%
  gt::gtsave(filename = "table1.html")

```


```{r}
cdidata <- cdidata %>% 
  mutate(CRM1000 = crimes/(pop/1000),
         region = fct_recode(factor(region), 
                             "Northeast" = "1", 
                             "North Central" = "2", 
                             "South" = "3", 
                             "West" = "4"),
         log_area = log(area),
         log_pop = log(pop),
         log_pop18 = log(pop18),
         log_pop65 = log(pop65),
         log_docs = log(docs),
         log_beds = log(beds),
         log_crimes = log(crimes),
         log_hsgrad = log(hsgrad),
         log_bagrad = log(bagrad),
         log_poverty = log(poverty),
         log_unemp = log(unemp),
         log_pcincome = log(pcincome),
         log_totalinc = log(totalinc),
         log_CRM1000 = log(CRM1000))

hist.data.frame(cdidata)

```



```{r}

# left out id, cty, state, crimes
# all variables aside from hsgrad and region are log transformed
selectcdi <- cdidata %>% 
  dplyr::select(c(log_CRM1000, log_area, log_pop, log_pop18, log_pop65, log_docs, 
                  log_beds, hsgrad, log_bagrad, log_poverty, log_unemp, 
                  log_pcincome, log_totalinc, region)) %>% 
  labelled::set_variable_labels(log_area = "Log land area (mi)",
                                log_pop = "Log total population",
                                log_pop18 = "Log percent of population aged 18-34",
                                log_pop65 = "Log percent of population aged 65+",
                                log_docs = "Log number of active physicians",
                                log_beds = "Log number of hospital beds",
                                log_CRM1000 = "Log total serious crimes per 1000 population",
                                hsgrad = "Percent high school graduates",
                                log_bagrad = "Log percent bachelor’s degrees",
                                log_poverty = "Log percent below poverty level",
                                log_unemp = "Log percent unemployment",
                                log_pcincome = "Log per capita income (USD)",
                                log_totalinc = "Log total personal income (millions USD)",
                                region = "Geographic region")
```


```{r}
# slr for selectcdi vars
s1 <-  lm(log_CRM1000~log_area, data=selectcdi)
s2 <-  lm(log_CRM1000~log_pop, data=selectcdi)
s3 <-  lm(log_CRM1000~log_pop18, data=selectcdi)
s4 <-  lm(log_CRM1000~log_pop65, data=selectcdi)
s5 <-  lm(log_CRM1000~log_docs, data=selectcdi)
s6 <-  lm(log_CRM1000~log_beds, data=selectcdi)
s7 <-  lm(log_CRM1000~hsgrad, data=selectcdi)
s8 <-  lm(log_CRM1000~log_bagrad, data=selectcdi)
s9 <-  lm(log_CRM1000~log_poverty, data=selectcdi)
s10 <- lm(log_CRM1000~log_unemp, data=selectcdi)
s11 <- lm(log_CRM1000~log_pcincome, data=selectcdi)
s12 <- lm(log_CRM1000~log_totalinc, data=selectcdi)
s13 <- lm(log_CRM1000~region, data=selectcdi)

varnames <- c("Log land area (mi)", 
              "Log total population", 
              "Log percent of population aged 18-34", 
              "Log percent of population 65+", 
              "Log number of active physicians", 
              "Log number of hospital beds",
              "Percent high school graduates", 
              "Log percent bachelor's degrees", 
              "Log percent below poverty level", 
              "Log percent unemployment", 
              "Log per capita income (USD)",
              "Log total personal income (millions USD)", 
              "North Central (ref: Northeast)", 
              "South (ref: Northeast)", 
              "West (ref: Northeast)")

b <- c(summary(s1)$coefficients[2,1],
       summary(s2)$coefficients[2,1],
       summary(s3)$coefficients[2,1],
       summary(s4)$coefficients[2,1],
       summary(s5)$coefficients[2,1],
       summary(s6)$coefficients[2,1],
       summary(s7)$coefficients[2,1],
       summary(s8)$coefficients[2,1],
       summary(s9)$coefficients[2,1],
       summary(s10)$coefficients[2,1],
       summary(s11)$coefficients[2,1],
       summary(s12)$coefficients[2,1],
       summary(s13)$coefficients[2,1],
       summary(s13)$coefficients[3,1],
       summary(s13)$coefficients[4,1])

p <- c(summary(s1)$coefficients[2,4],
       summary(s2)$coefficients[2,4],
       summary(s3)$coefficients[2,4],
       summary(s4)$coefficients[2,4],
       summary(s5)$coefficients[2,4],
       summary(s6)$coefficients[2,4],
       summary(s7)$coefficients[2,4],
       summary(s8)$coefficients[2,4],
       summary(s9)$coefficients[2,4],
       summary(s10)$coefficients[2,4],
       summary(s11)$coefficients[2,4],
       summary(s12)$coefficients[2,4],
       summary(s13)$coefficients[2,4],
       summary(s13)$coefficients[3,4],
       summary(s13)$coefficients[4,4])


slrsummary <- data.frame(Variable = varnames,
                     Coefficient = round(b,3), 
                     pvalue = round(p,3))

slrsummary$pvalue[slrsummary$pvalue == 0.000] = "<0.001"

    
slrsummary %>% 
  gt() %>% 
  tab_header(title = md("**Simple Linear Regression of Crime Rate** <br>
                        **per 1000 Population on Each Variable**")) %>% 
  gtsave(filename = "slr.html")
```

```{r}

#model with no interactions
main1 <- lm(log_CRM1000 ~ ., data = selectcdi)
summary(main1)

# based on corrplot, significant correlation between the following pairs:
# log_pop/log_docs (0.9), log_pop/log_beds (0.84), log_pop/log_totalinc (0.98)
# log_docs/log_beds (0.9), log_docs/log_total_inc (0.91), log_beds/log_totalinc (0.81)

#model with no interactions, excluding log_pop and log_docs

main2 <- lm(log_CRM1000 ~ . -log_pop -log_docs, data = selectcdi)
summary(main2)

theme_gtsummary_journal(journal = "jama")
#> Setting theme `JAMA`
theme_gtsummary_compact()
#> Setting theme `Compact`

main2 %>% 
  tbl_regression() %>% 
  bold_p() %>% 
  modify_caption("**Main Effects Multiple Regression Model of Log Crime Rate on 11 Predictors**") %>% 
  as_gt() %>%
  gt::gtsave(filename = "finalmaineffects.html")

mainvars <- selectcdi %>% 
  dplyr::select(-log_pop, -log_docs)


```


```{r}

# model with 2-way interactions
full1 <- lm(log_CRM1000~.^2, data = mainvars)
summary(full1)
steplm1 <- stepAIC(full1, direction = "both") # stepwise based on AIC

n <- nrow(mainvars)
steplm2 <- stepAIC(full1, direction = "both", k = log(n)) # stepwise based on BIC/SBC

steplm1$anova #AIC stepwise selection
steplm2$anova #BIC stepwise selection
```
```{r}
# summaries of final models 

aiclm <- lm(log_CRM1000 ~ log_area + log_pop18 + log_pop65 + log_beds + hsgrad + 
    log_bagrad + log_poverty + log_unemp + log_pcincome + log_totalinc + 
    region + log_area:log_pop18 + log_area:log_unemp + log_area:log_pcincome + 
    log_pop18:log_pop65 + log_pop18:log_bagrad + log_pop18:log_unemp + 
    log_pop18:log_pcincome + log_pop18:region + log_pop65:region + 
    log_beds:log_poverty + log_beds:log_totalinc + log_beds:region + 
    hsgrad:log_bagrad + hsgrad:region + log_bagrad:log_pcincome + 
    log_poverty:log_totalinc + log_unemp:region + hsgrad:log_pcincome, data=mainvars)

biclm <- lm(log_CRM1000 ~ log_area + log_pop18 + log_beds + hsgrad + log_bagrad + 
    log_poverty + log_unemp + log_pcincome + log_totalinc + region + 
    log_area:log_beds + log_area:log_poverty + log_area:log_unemp + 
    log_beds:log_totalinc + hsgrad:log_bagrad + log_bagrad:log_pcincome, data=mainvars)


summary(aiclm)
summary(biclm)

theme_gtsummary_journal(journal = "jama")
#> Setting theme `JAMA`
theme_gtsummary_compact()
#> Setting theme `Compact`

aiclm %>% 
  tbl_regression() %>% 
  bold_p() %>% 
  as_gt() %>% 
  gt::tab_source_note(gt::md("This model has a multiple R-squared of 0.65 and adjusted R-squared of 0.62")) %>% 
  gt::tab_source_note(gt::md("F-statistic: 18.35 on 41 and 398 DF, p-value: < 0.001")) %>% 
  gt::gtsave(filename = "aicmodel.html")

biclm %>% 
  tbl_regression() %>% 
  bold_p() %>% 
  as_gt() %>% 
  gt::tab_source_note(gt::md("This model has a multiple R-squared of 0.59 and adjusted R-squared of 0.58")) %>% 
  gt::tab_source_note(gt::md("F-statistic: 34.2 on 18 and 421 DF, p-value: < 0.001")) %>% 
  gt::gtsave(filename = "bicmodel.html")


```

