---
title: "Midterm Output"
author: "Lillian Chen"
date: "10/29/2021"
output: pdf_document
---


```{r}
library(tidyverse)
library(kableExtra)
```


```{r}
#check of anova table for question 4
#numbers do not match up exactly - calculations for the table utilized the printed numbers
#on the partially filled out table

options(knitr.kable.NA = '')
k <- 4
N <- 13+13+14+14
df_b <- k-1
df_w <- N-k
df_tot <- N-1

mean11 <- 341.69
mean12 <- 312.92
mean13 <- 321.43
mean14 <- 302.00
(grandmean <- (13*mean11 + 13*mean12 + 14*mean13 + 14*mean14)/N)

ssb <- 13*(mean11-grandmean)^2 + 13*(mean12-grandmean)^2 + 
       14*(mean13-grandmean)^2 + 14*(mean14-grandmean)^2
ssw <- 12*(18.12)^2 + 12*(23.20)^2 + 13*(21.72)^2 + 13*(17.02)^2
msb <- ssb/df_b
msw <- ssw/df_w
Fstat <- msb/msw
p <- 1 - pf(Fstat, k-1, N-k)
```

```{r}
q4 <- data.frame(Source = c("Between groups (Treatment)", 
                             "Within groups (Error)", 
                             "Total"),
                  df = c(k-1, N-k, N-1),
                  SS = c(ssb, ssw, ssb+ssw),
                  MS = c(msb, msw, (ssb+ssw)/(N-1)),
                  F = c(Fstat, NA, NA),
                  p = c(p, NA, NA))

kbl(q4, booktabs = T, 
    caption = "ANOVA Table Question 4") %>% 
  kable_styling(latex_options = c("hold_position"))
```

```{r q4extracredit}

(samplemean <- grandmean)
(s_p <- sqrt(405.942))
q4g <- data.frame(groupmeans = c(341.69,312.92,321.43,302.00),
                  groupsds = c(18.12,23.20,21.72,17.02))
q4g %>% 
  summarise(across(c(groupmeans,groupsds), sd, .names = "{.col}.sd"))

(r <- (sum((q4g$groupmeans-samplemean)*(q4g$groupsds-s_p))/(4-1))/(16.78955*2.921889))

#check
cor(q4g$groupmeans, q4g$groupsds, use="pairwise.complete.obs")

```

```{r q5}
q5data <- data.frame(x=c(1,2,4,5,10),
                     y=c(4,3,2,1,10))

#check for question 5a
cor(q5data$x, q5data$y, use="pairwise.complete.obs")

#check for question 5b
q5lm <-lm(y~x,data=q5data)
summary(q5lm)

#question 5c
(s_e <- summary(q5lm)$sigma)
(se_b1 <- s_e/sqrt(sum((q5data$x-4.4)^2)))
(se_b0 <- s_e*sqrt(1/5 + (4.4)^2/sum((q5data$x-4.4)^2)))
```


```{r q5d}
#remove 10,10
q5ddata <- data.frame(x=head(q5data$x,-1),
                      y=head(q5data$y,-1))

#calculate new means and sds
q5ddata %>% 
  summarise(across(c(x,y), mean, .names = "{.col}.smean"),
            across(c(x,y), var, .names = "{.col}.svar"))

#new sample correlation
(r <- cov(q5ddata$x,q5ddata$y)/(3.333*1.667))

#check for question 5e
q5dlm <- lm(y~x, data=q5ddata)
summary(q5dlm)
```

